/*
===============================================================================================================
Magnitude Analysis

Purpose:
  - Compare the measure value by categories
  - To help in understanding the importance of different categories
===============================================================================================================
*/

-- Total number of customers per country
SELECT
	country,
	COUNT(*) AS Number
FROM gold.dim_customers
GROUP BY country

-- Total customers per gender
SELECT
	gender,
	COUNT(*) AS Number
FROM gold.dim_customers
GROUP BY gender


-- Total products by category
SELECT
	category,
	COUNT(*) AS Number
FROM gold.dim_products
GROUP BY category

-- Average cost of product by category
SELECT
	category,
	AVG(cost) AS Number
FROM gold.dim_products
GROUP BY category

-- Total revenue generated for each category
SELECT
	p.category,
	SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY Total_revenue DESC

-- Total revenue generated by each customer
SELECT
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS Total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON	c.customer_key = s.customer_key
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY Total_revenue DESC

-- Distribution of sold items across countries
SELECT
	c.country,
	p.product_id,
	SUM(f.quantity) AS Amount_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
LEFT JOIN gold.dim_products p
ON	f.product_key = p.product_key
GROUP BY c.country, p.product_id
ORDER BY Amount_sold DESC










